SELECT TOP (1000) [ID]
      ,[STATUS]
      ,[SYMBOL]
      ,[ORDER_SIDE]
      ,[ORDER_TYPE]
      ,[QUANTIY]
      ,[OPEN_PRICE]
      ,[CLOSE_PRICE]
      ,[CLOSE_TYPE]
      ,[SIGNAL_TYPE]
      ,[BINANCE_ORDER_ID]
      ,[INSERT_DATETIME]
  FROM [coins].[dbo].[PROCESS]

  -- ORDER İŞLEMİ FİLLED - PARTIAL FILLED OLDUĞU AN TERS İŞLEM KAPATMA İŞLEM EMRİ AÇILACAK.. 
  -- CLOSE_PRICE DEĞİŞTİKÇE STATUS RENEW 'E İNDİKATÖR GÜNCELLEYEEK. CENGİZ TARAFI RENEW'LER İÇİN TERS EMİRDE GÜNCELLEME YAPICAK.. 
  -- EMİR GERÇEKLEŞTİKTEN SONRA RENEW->OPENED A UPDATE EDİLECEK



