SELECT TOP (1000) [SiraNo]
      ,[CoinKodu]
      ,[MinMiktar]
      ,[AktifDurumu]
      ,[FiyatAdimi]
      ,[5m]
      ,[15m]
      ,[30m]
      ,[1h]
      ,[4h]
      ,[1d]
      ,[1m]
      ,[SinyalVermeAcKapa]
      ,[RSI]
      ,[WR]
      ,[BB]
  FROM [coins].[dbo].[CoinListesi]
